version: "3.8"

services:
  mikan_build:
    build:
      context: ./
      args:
        user: ${USER}
        display: ${DISPLAY}
    hostname: mikan
    ports:
      - "34322:22"
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /etc/localtime:/etc/localtime
      - /etc/passwd:/etc/passwd
      - /etc/shadow:/etc/shadow
      - /etc/group:/etc/group
      - ~/work:/home/${USER}/work
      - ~/.ssh:/home/${USER}/.ssh
      - ~/.bashrc:/home/${USER}/.bashrc
    entrypoint: [/usr/sbin/sshd, -D]
