MACRO(ADD_SUBDIRS)
  FILE(GLOB sub_dirs RELATIVE ${CMAKE_CURRENT_SOURCE_DIR} *)
  FOREACH(dir IN LISTS sub_dirs)
    IF (IS_DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR}/${dir})
      IF (EXISTS ${CMAKE_CURRENT_SOURCE_DIR}/${dir}/CMakeLists.txt)
        add_subdirectory(${dir})
      ENDIF()
    ENDIF()
  ENDFOREACH()
ENDMACRO()

MACRO(ADD_TEST)
  FILE(GLOB file_list "${CMAKE_CURRENT_SOURCE_DIR}/*.cpp")
  set(library_file_list)
  foreach(fname IN LISTS file_list)
    string(REGEX REPLACE "${CMAKE_CURRENT_SOURCE_DIR}/test_.*\.cpp" "" out ${fname})
    list(APPEND library_file_list "${out}")
  endforeach()

  if (library_file_list)
    add_library(${module_name} ${library_file_list})
  endif()
  
  file(GLOB file_list "test_*.cpp")
  foreach(fname IN LISTS file_list)
    get_filename_component(basename ${fname} NAME_WE)
    add_executable(${module_name}_${basename} ${fname})
    target_link_libraries(${module_name}_${basename} ${library_file_list} ${EXTERNAL_LIBS})
  endforeach()
ENDMACRO()  
