MACRO(ADD_EXES parent_dir)
  # CMakeLists.txt が存在しないサブディレクトリにあるcppファイルからexeを生成する
  # サブディレクトリ内のファイルを走査してexecutableを作成する。
  FILE(GLOB children RELATIVE ${parent_dir} ${parent_dir}/*)
  message("-- ADD BELOW SUBDIR IN ${parent_dir} AS EXECUTABLES")
  FOREACH(child IN LISTS children)
    IF(IS_DIRECTORY ${parent_dir}/${child})
      IF(NOT EXISTS ${parent_dir}/${child}/CMakeLists.txt)
        message("      ${child}")
        FILE(GLOB file_list "${parent_dir}/${child}/[a-z]*.c")
        FOREACH(fname IN LISTS file_list)
          get_filename_component(bname ${fname} NAME_WE)
          add_executable(${child}_${bname} ${fname})
        ENDFOREACH()
      ENDIF()
    ENDIF()
  ENDFOREACH()
  message("-- END ADD EXECUTABLE")
ENDMACRO()
